### PR TITLE
password encryption included / tested for double entries

### LINKED ISSUE #13: 11-password-encryption
As a user
So I don't need to worry about password security
I want my password to be encrypted

### PR DESCRIPTION
**Pull request by ghost**
Closes #13  - password encryption

Functionality pulled across from bookmark manager.

### CODE REVIEW

**Comment by lewmoore** [comment]
:shipit:

**Comment by alextwilson** [comment]
👀 👍 2 👨

**Comment by Gleoman** [comment]
:shipit:

**Comment by Leigan0** [comment]
🥘

**Review by ghost — COMMENTED** [review]
🇲🇴

**Pull request merged**
