### PR TITLE
4 add space info

### PR DESCRIPTION
**Pull request by lewmoore**
Add multiple properties to the Space class to show price and description. 
Added these properties to the view
Refactor web helpers, tests and data_mapper setup to root

### CODE REVIEW

**Comment by lewmoore** [comment]
closes #15 and #4

**Comment by alextwilson** [comment]
LGTM

**Comment by lewmoore** [comment]
:shipit:

**Comment by Leigan0** [comment]
🥇

**Comment by Gleoman** [comment]
:shipit:

**Pull request merged**
